//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarChargingData
    {
        public int StationID { get; set; }
        public string TimeRemaining { get; set; }
        public string KWHUsage { get; set; }
        public string Occupier { get; set; }
    
        public virtual CarChargingData CarChargingData1 { get; set; }
        public virtual CarChargingData CarChargingData2 { get; set; }
    }
}
