//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargingData
    {
        public int CarReg { get; set; }
        public string StationID { get; set; }
        public string TimeUsage { get; set; }
        public string KWHUsage { get; set; }
    }
}
